#ifndef PHP_BBS_ERRORNO_H
#define PHP_BBS_ERRORNO_H

/* 错误码 */

#define PHPBBS_ERROR_OK                 0
#define PHPBBS_ERROR_OK_MSG             ""

#define PHPBBS_ERROR_GENERAL            -100
#define PHPBBS_ERROR_GENERAL_MSG        "未知错误"
#define PHPBBS_ERROR_BOARD_NONEXIST     -101
#define PHPBBS_ERROR_BOARD_NONEXIST_MSG "错误的版面"
#define PHPBBS_ERROR_BOARD_INVISIBLE    -102
#define PHPBBS_ERROR_BOARD_INVISIBLE_MSG "错误的版面"
#define PHPBBS_ERROR_BOARD_DENYPOST     -103
#define PHPBBS_ERROR_BOARD_DENYPOST_MSG "对不起，您已被停止在此版的发文权限"
#define PHPBBS_ERROR_BOARD_NOPOSTPERM   -104
#define PHPBBS_ERROR_BOARD_NOPOSTPERM_MSG "您无权在此版发表文章"
#define PHPBBS_ERROR_BOARD_READONLY     -105
#define PHPBBS_ERROR_BOARD_READONLY_MSG "本版已被设置只读"
#define PHPBBS_ERROR_BOARD_DENYMOD      -106
#define PHPBBS_ERROR_BOARD_DENYMOD_MSG  "不能修改他人文章"

#define PHPBBS_ERROR_USER_NONEXIST      -201
#define PHPBBS_ERROR_USER_NONEXIST_MSG  "用户不存在"

#define PHPBBS_ERROR_POST_MODPERM       -301
#define PHPBBS_ERROR_POST_MODPERM_MSG   "您无权修改这篇文章"
#define PHPBBS_ERROR_POST_NONEXIST      -302
#define PHPBBS_ERROR_POST_NONEXIST_MSG  "帖子不存在"

#define PHPBBS_ERROR_ATTACH_CLIMIT      -901
#define PHPBBS_ERROR_ATTACH_CLIMIT_MSG  "附件数量超过限制"
#define PHPBBS_ERROR_ATTACH_SLIMIT      -902
#define PHPBBS_ERROR_ATTACH_SLIMIT_MSG  "附件总大小超过限制"
#define PHPBBS_ERROR_ATTACH_DELNONE     -903
#define PHPBBS_ERROR_ATTACH_DELNONE_MSG "要删除的附件不存在"
#define PHPBBS_ERROR_ATTACH_INVALIDNAME -904
#define PHPBBS_ERROR_ATTACH_INVALIDNAME_MSG "无效的文件名"
#define PHPBBS_ERROR_ATTACH_DUPNAME     -905
#define PHPBBS_ERROR_ATTACH_DUPNAME_MSG "存在同名文件"
#define PHPBBS_ERROR_ATTACH_ADDPERM     -906
#define PHPBBS_ERROR_ATTACH_ADDPERM_MSG "没有权限添加附件"


#define ERRS(name) \
    case PHPBBS_ERROR_##name: \
        desc = PHPBBS_ERROR_##name##_MSG; \
        break;
    
#define ALL_PHPBBS_ERRORS \
    ERRS(OK) \
    \
    ERRS(GENERAL) \
    ERRS(BOARD_NONEXIST) \
    ERRS(BOARD_INVISIBLE) \
    ERRS(BOARD_DENYPOST) \
    ERRS(BOARD_NOPOSTPERM) \
    ERRS(BOARD_READONLY) \
    ERRS(BOARD_DENYMOD) \
    \
    ERRS(USER_NONEXIST) \
    \
    ERRS(POST_MODPERM) \
    ERRS(POST_NONEXIST) \
    \
    ERRS(ATTACH_CLIMIT) \
    ERRS(ATTACH_SLIMIT) \
    ERRS(ATTACH_DELNONE) \
    ERRS(ATTACH_INVALIDNAME) \
    ERRS(ATTACH_DUPNAME) \
    ERRS(ATTACH_ADDPERM) \


#define RETURN_ERROR(name)  RETURN_LONG(PHPBBS_ERROR_##name)

#endif //PHP_BBS_ERRORNO_H


