#!/bin/sh

FTPSCRIPT=etc/saveanno
TMPFILE=reclog/tmpMakeAnnoDir
BBSHOME=/home/bbs

cd $BBSHOME
bin/printboards .BOARDS > boardlist
mv /backup/bbs/Announce.bak /backup/bbs/Announce.bak.bak
rm -rf /backup/bbs/Announce.bak.bak&
mv /backup/bbs/Announce /backup/bbs/Announce.bak
mkdir /backup/bbs/Announce
bin/MakeTar /backup/bbs/Announce> reclog/Maketar.log
cat $FTPSCRIPT | grep -v bye| grep -v %filename%|grep -v EOF > $TMPFILE
cat << EOF >>  $TMPFILE
lcd /backup/bbs/Announce
mput *.tgz
mkdir groups
cd groups
lcd $BBSHOME/0Announce/groups
put .Names
EOF
for i in $BBSHOME/0Announce/groups/* ; do
if [ -d $i ] ; then
DIRNAME=`basename $i`
cat << EOF >> $TMPFILE
lcd $i
mkdir $DIRNAME
cd $DIRNAME
put .Names
cd ..
EOF
echo hehe ;
fi
done
cat << FOF >> $TMPFILE
cd ..
mkdir finish
bye
EOF
FOF
ftp -n < $TMPFILE
rm -f $TMPFILE
