#ifndef __SYSNAME_H_
#define __SYSNAME_H_

#define BBSUID 			501
#define BBSGID 			501

/** 定义使用缺省的函数 */
#define USE_DEFAULT_SECODE
#define USE_DEFAULT_ALPHABET
#define USE_DEFAULT_PERMSTRINGS
#define USE_DEFAULT_DEFINESTR
#define USE_DEFAULT_MAILBOX_PROP_STR
#define USE_DEFAULT_LEVELCHAR
#define USE_DEFAULT_MODE
#define USE_DEFAULT_MULTILOGIN_CHECK
#define USE_DEFAULT_USER_LIFE
#define USE_DEFAULT_ANNOUNCE_FILENAME
#define USE_DEFAULT_GET_POSTTIME
#define USE_DEFAULT_SET_POSTTIME
#define USE_DEFAULT_SET_POSTTIME2
#define USE_DEFAULT_BUILD_BOARD
#define USE_DEFAULT_MAIL_LIMIT /*邮件容量限制*/



#endif


