#!/bin/sh
# a mini-configure to simplify installation

CPP=$1

echo "/* don't change -- generated by miniconf.sh */" > miniconf.h

# check unistd
if [ -f /usr/include/unistd.h ]; then
	echo "#define UNISTD"	>> miniconf.h
else
	echo '#include <unistd.h>' > minitest.c
	err=`eval "($CPP minitest.c >/dev/null) 2>&1"` 
	if [ -z "$err" ]; then 
		echo "#define UNISTD"	>> miniconf.h
	fi
	rm -f minitest*
fi

